
# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: True
# Data training arguments
dataset_mixer:
  ./data/seed-data/DSAT_to_SAT: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
do_eval: true
# optional (RPO: DPO+NLL to make it more stable)
rpo_alpha: 0.001
eval_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: Qwen2.5-7B-Instruct-wildfeedback-seed
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 3
optim: rmsprop
# optim: adamw_torch
output_dir: ./outputs/Qwen2.5-7B-Instruct-wildfeedback-seed
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: true
hub_strategy: "checkpoint"
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1